### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by daniel-dinu** [P-H-C/phc-winner-argon2#85] opened 2016-01-23 21:33 UTC
Given the number of supported platforms and that it is hard to test each code change on all supported platforms, I think it might be useful to have a CI system to automatically detect and eventually avoid the compilation errors.

It would be nice to build at least on the following systems:
- Debian/Ubuntu
- Mac OS X
- Windows

Any volunteer?

**Comment by lucab** [comment] 2016-01-23 22:03
Other github projects I touched use travis-ci (Mac + Linux) and appveyor (Windows) for CI.
I guess another good step is to start introducing a testsuite, to catch regressions earlier.

**Comment by technion** [comment] 2016-01-24 01:09
Been raised before in #28.

**Comment by hynek** [comment] 2016-01-25 08:28
+1 for also using AppVeyor because making sure that code compiles on all VisualStudios is rather finicky (cf. #91).  You’ll have to use msinttypes though.

**Comment by ranisalt** [comment] 2016-02-01 18:07
Now that #89 is merged it'd be nice to CI this repository, and it would also be nice to check code coverage for tests too. I use lcov to check coverage on [node-argon2](https://github.com/ranisalt/node-argon2) ([check here](https://github.com/ranisalt/node-argon2/blob/master/.travis.yml#L20)) but test compilation requires [extra flags to be set](https://github.com/ranisalt/node-argon2/blob/master/binding.gyp#L37-L38).

**Comment by technion** [comment] 2016-02-02 02:17
Regrettably I'm not familiar with Appveyor - but now that #89 is in I'll be creating a Travis config to cover the Ubuntu/Mac side.

**Comment by hynek** [comment] 2016-02-02 06:41
Would it be possible to sneak in extra compiler flags?  There are a few that complain about C99isms but might be too modern to be part of the regular build chain.

**Comment by technion** [comment] 2016-02-02 07:15
@hynek  I think this is the perfect place for such a thing - if you can advise what they are I will add.

**Comment by hynek** [comment] 2016-02-02 09:16
`-Werror=declaration-after-statement` would be one important one that would have prevented two recent regressions.  I’m sure there are more, but I’m a bit out of the C game (and not regretting it really :))

**Comment by technion** [comment] 2016-02-02 09:48
@hynek pushed.

**Comment by hynek** [comment] 2016-02-02 13:04
maybe you could try `-pedantic-errors` too?  not sure what it exactly does tho.  as said, I’m a bit rusty. :)

**Comment by ranisalt** [comment] 2016-02-02 15:50
Why not go straight to `-Wall -Wextra -Wpedantic` in a test? And people please `make test` before pushing and it'll be fine :)

**Comment by technion** [comment] 2016-02-02 20:44
Note it's already running -Wall -Wextra -Werror.
I had to include -Wno-type-limits as the codebase has many warnings come out of that.

With #99 merged, @daniel-dinu - can we get someone to visit travis-ci.org and enable the service on this repo?

**Comment by ranisalt** [comment] 2016-02-02 21:00
Oh yes, there's a lot of unsigned int < 0 comparisons. They probably get striped away by compiler optimizations but are they REALLY needed?

**Comment by ranisalt** [comment] 2016-02-17 21:00
Nice it was implemented but please don't play in the master branch. The history is now full of trash commits with duplicate messages and single-line edits. Rather work in a branch where you can rewrite history, then merge to master.

**Comment by daniel-dinu** [comment] 2016-02-17 21:21
You are right. Sorry for the pollution!

**Comment by ranisalt** [comment] 2016-02-17 21:30
Oh, also there are some code paths that don't need to be tested, such as
```
    if (Argon2_d != type && Argon2_i != type) {
        return ARGON2_INCORRECT_TYPE;
    }
```
([source](https://github.com/P-H-C/phc-winner-argon2/blob/6b66b7e82501b580d6c8acb7bb2af45bf2372fa9/src/argon2.c#L120-L122))
I'm not sure about C, but at least in C++ enum types are checked and any value not defined in the `Argon2_type` enum would cause a type error, so this branch should not be reachable under normal conditions and thus does not need to be covered.

Some other paths could be ignored to raise the code coverage while keeping it well tested, the majority of them are testing for memory allocation errors which are very hard to test.

**Comment by technion** [comment] 2016-02-17 22:14
Yes, I'm not convinced code coverage makes a huge amount of sense in a C project.

I strive for 100% coverage in, eg, Ruby, but C includes a lot of assertions for things like malloc and threading failures, and "defensive" code that isn't technically possible to reach. Whilst I do note that I can actually trigger some of these failures by running the test suite on an AWS Nano (works as intended BTW), attempting to replicate it in a test suite is going to require heaps of unportable code, that is more likely to contain bugs than detect them. In particular, cases where you have two consecutive allocations, and you would need to limit memory such that the first one succeeds, but the second one fails.

There is also a tonne of untested code in the form of one line wrapper functions that are clearly trivial in their nature. I don't object to testing these but it feels like a lot of work for little gain.

For reference, the codebase also comes up clean in Facebook's Infer Static Analyzer, following my last PR.

I am writing a PR for the obvious places I can improve coverage.

**Comment by technion** [comment] 2016-02-23 11:19
Can I suggest closing this? We already have #107 for the only remaining component.

**Closed** 2016-02-23 11:23 UTC
