### ISSUE TITLE
inconsistency with argon2_verify() and the "associated data" field

### ISSUE THREAD

**Issue by eli-collins** [P-H-C/phc-winner-argon2#143] opened 2016-06-17 21:03 UTC
I was looking through the source to learn more about the hash string format, and noticed in the comment above `decode_string()` there's a reference to a "keyid" and "data" parameters, which seem to correspond to the `secret` and `ad` fields in the argon2_context. 

However, it looks like keyid isn't actually parsed by `decode_string()` or written by `encode_string()`; including that in the hash just results in a decode error.

On the other hand, the `data=` parameter *is* parsed by `decode_str()`, and written to `ctx.ad`.  However, `argon2_verify()` seems to silently discard this field, instead of passing along to `argon2_context()`.  

This results in the case where a hash of "password" such as `$argon2i$v=19$m=512,t=2,p=2$c29tZXNhbHQ$uEeXt1dxN1iFKGhklseW4w` will still verify correctly if a data parameter is inserted in the string, no matter what the data parameter is!  For example, `$argon2i$v=19$m=512,t=2,p=2,data=c29tZWRhdGE$c29tZXNhbHQ$uEeXt1dxN1iFKGhklseW4w` still verifies correctly against "password". 

I was expecting that second hash to either 1) fail to parse, or 2) have the `ctx.ad` value passed on to `argon2_context()`, in which case it would fail to verify because the digest no longer matched.  (In the case of option 2, I think the correct hash string for "password" would be `$argon2i$v=19$m=512,t=2,p=2,data=c29tZWRhdGE$c29tZXNhbHQ$KgHyCesFyyjkVkihZ5VNFw`).

I'm guessing the 'data' parameter was either a work-in-progress feature intended to be fleshed out, or a remnant of some old code that needs to be stripped.  But wanted to clarify, as I'm writing a Python wrapper, and wanted to make sure I accounted for edge cases. 

Thanks!

- Eli

**Comment by sneves** [comment] 2016-06-19 17:50
This looks like a legitimate bug. `argon2_verify` is calling `argon2_hash`, which does not have an `ad` input. The simplest solution seems to be adding `ad` and `adlen` to `argon2_hash`, though I don't quite like the gigantic number of arguments there.

`keyid` was meant to be an _identifier_ for a secret key; this effectively means that it can't be used in a generic library since it's application-dependent. The solution would be an input callback to transform an identifier into a key, but I'm not sure there's enough interest for that.

**Comment by technion** [comment] 2016-06-22 03:29
Is this something that is perhaps better addressed by removing keyid from the spec?

Any sort of key id lookup system is going to be pulling that associated key from an external source, which in turn will likely involve utilising a higher level framework to access a database, config file or similar. There's a lot of room to suggest keyid would be every bit as effective, as far as its original design goal, by having it sit in its own column in a database alongside the user password.

**Comment by sneves** [comment] 2016-06-22 15:00
I tend to agree; I had completely forgotten the existence of `keyid`, and apparently so had everyone else.

**Comment by khovratovich** [comment] 2016-06-22 15:41
I think `keyid` can be removed, but `ad` needs special attention. 
For backward compatibility it might be better to disable parsing it as long as it is not fed to any function.
However, I just realized that we do not have a function that accepts pure `key` and `ad` pointers, so to use them one should fill the `context` struct itself. Maybe we should introduce one such function, then `ad` can be parsed again.

**Comment by SparkDustJoe** [comment] 2016-08-17 01:50
Is KeyId tied to Secret?

**Comment by josephlr** [comment] 2016-10-25 19:36
I think there is a fairly simple solution to this problem. Currently encoding/decoding is only supported in contexts where there is no associated data and no secret. Thus, the only encoding strings that can be produced don't include a `data` or `keyid` field. 

I think the simplest thing to do is to simply remove the `keyid` and `data` fields from `encode_string()` and `decode_string()`. For @khovratovich's point about backward compatibility, this will only break decoding for manually created strings, which I think is acceptable.

This means that any user using the `ad` or `secret` parameters will need to feed them manually into the context functions. Again, this seems acceptable as it is way less common to use these parameters. 

@SparkDustJoe It looks like the KeyId was intended to be filled with some external identifier for a key, but it was never actually used.

**Closed** 2016-10-29 09:12 UTC
Labels: bug

**Comment by Leont** [comment] 2023-03-08 00:32
> There's a lot of room to suggest keyid would be every bit as effective, as far as its original design goal, by having it sit in its own column in a database alongside the user password.

I am absolutely puzzled by this assertion. By that logic we might as well cut the hash up in pieces and store it in half a dozen fields (for all the various components). Needing more than one field to implement does actually complicate things because existing infrastructure everything to be contained in one field. I will need to change not only the database scheme, but also every components between the database and my password checker, because the existing generic components are all made for the scenario that everything is in one value. It's a huge headache really.
